/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bi4vmr_study_jni_datatype_JNIClass */

#ifndef _Included_net_bi4vmr_study_jni_datatype_JNIClass
#define _Included_net_bi4vmr_study_jni_datatype_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bi4vmr_study_jni_datatype_JNIClass
 * Method:    passBasicTypes
 * Signature: (ZID)V
 */
JNIEXPORT void JNICALL Java_net_bi4vmr_study_jni_datatype_JNIClass_passBasicTypes
  (JNIEnv *, jobject, jboolean, jint, jdouble);

/*
 * Class:     net_bi4vmr_study_jni_datatype_JNIClass
 * Method:    passString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bi4vmr_study_jni_datatype_JNIClass_passString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_bi4vmr_study_jni_datatype_JNIClass
 * Method:    passStringArray
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_bi4vmr_study_jni_datatype_JNIClass_passStringArray
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     net_bi4vmr_study_jni_datatype_JNIClass
 * Method:    returnBasicTypes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_bi4vmr_study_jni_datatype_JNIClass_returnBasicTypes
  (JNIEnv *, jobject);

/*
 * Class:     net_bi4vmr_study_jni_datatype_JNIClass
 * Method:    returnString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bi4vmr_study_jni_datatype_JNIClass_returnString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
