# 版本号
[versions]
# ----- 实用工具 -----
apacheCommons-io = "1.3.2"
slf4j-simple = "2.0.9"
gson = "2.10.1"


# ----- 数据存储 -----
sqlite = "3.46.0.0"
mariadb = "3.2.0"
mybatis = "3.5.16"


# ----- 测试工具 -----
junit-jupiter = "5.10.2"


# 组件
[libraries]
# ----- 实用工具 -----
# Apache通用工具(IO)
apacheCommons-io = { group = "org.apache.commons", name = "commons-io", version.ref = "apacheCommons-io" }

# SLF4J-Simple
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j-simple" }

# GSON
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }


# ----- 数据存储 -----
# JDBC驱动(SQLite)
jdbc_sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
# JDBC驱动(MariaDB)
jdbc_mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }

# MyBatis
mybatis = { group = "org.mybatis", name = "mybatis", version.ref = "mybatis" }


# ----- 测试工具 -----
# JUnit-Jupiter
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
