/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bi4vmr_study_jni_base_JNIClass */

#ifndef _Included_net_bi4vmr_study_jni_base_JNIClass
#define _Included_net_bi4vmr_study_jni_base_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bi4vmr_study_jni_base_JNIClass
 * Method:    printInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bi4vmr_study_jni_base_JNIClass_printInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
