# 版本号
[versions]
# ----- Java：通用工具 -----
java_gson = "2.10.1"
java_slf4j_simple = "2.0.9"


# ----- Java：数据存储 -----
java_jdbc_sqlite = "3.46.0.0"
java_jdbc_mariadb = "3.2.0"
java_mybatis = "3.5.16"


# ----- Java：测试工具 -----
java_junit_jupiter = "5.10.2"


# ----- Kotlin：核心 -----
kotlin_core = "1.9.21"

kotlinx_coroutines = "1.7.3"
kotlinx_serial_json = "1.6.2"


# ----- Kotlin：Gradle插件 -----
kotlin_gradle_ksp = "1.9.21-1.0.16"


# ----- Android：核心 -----
android_agp = "7.4.2"

android_appcompat = "1.6.1"
android_material = "1.8.0"
android_constraintLayout = "2.1.4"

android_KTX_core = "1.10.1"
android_KTX_coroutine = "1.8.1"
android_KTX_lifecycleRuntime = "2.5.1"
android_KTX_lifecycleViewModel = "2.5.1"


# ----- Android：实用工具 -----
android_utilcodex = "1.31.1"


# ----- Android：图像处理 -----
android_glide-core = "4.16.0"

android_coil-core = "1.1.1"
android_coil-gif = "0.9.5"


# ----- Android：数据存储 -----
android_room = "2.5.1"


# 组件
[libraries]
# ----- Java：通用工具 -----
# GSON
java_gson = { group = "com.google.code.gson", name = "gson", version.ref = "java_gson" }

# SLF4J-Simple
java_slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "java_slf4j_simple" }


# ----- Java：数据存储 -----
# JDBC驱动(SQLite)
java_jdbc_sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "java_jdbc_sqlite" }
# JDBC驱动(MariaDB)
java_jdbc_mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "java_jdbc_mariadb" }

# MyBatis
java_mybatis = { group = "org.mybatis", name = "mybatis", version.ref = "java_mybatis" }


# ----- Java：测试工具 -----
# JUnit-Jupiter
java_junit_jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "java_junit_jupiter" }


# ----- Kotlin：核心 -----
# Kotlin标准库
kotlin_stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin_core" }

# Kotlin协程支持
kotlinx_coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx_coroutines" }
# Kotlin序列化支持(JSON)
kotlinx_serial_json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx_serial_json" }


# ----- Android：核心 -----
# AppCompat
android_appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "android_appcompat" }
# Material Design
android_material = { group = "com.google.android.material", name = "material", version.ref = "android_material" }
# 约束布局
android_constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "android_constraintLayout" }

# Android Kotlin扩展（核心）
android_KTX_core = { group = "androidx.core", name = "core-ktx", version.ref = "android_KTX_core" }
# Android Kotlin扩展（协程）
android_KTX_coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "android_KTX_coroutine" }
# Android Kotlin扩展（Lifecycle-Runtime）
android_KTX_lifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "android_KTX_lifecycleRuntime" }
# Android Kotlin扩展（Lifecycle-ViewModel）
android_KTX_lifecycleViewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "android_KTX_lifecycleViewModel" }


# ----- Android：实用工具 -----
# UtilCodeX
android_utilcodex = { group = "com.blankj", name = "utilcodex", version.ref = "android_utilcodex" }


# ----- Android：图像处理 -----
# Glide
android_glide-core = { group = "com.github.bumptech.glide", name = "glide", version.ref = "android_glide-core" }
android_glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "android_glide-core" }

# Coil
android_coil-core = { group = "io.coil-kt", name = "coil", version.ref = "android_coil-core" }
android_coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "android_coil-gif" }


# ----- Android：数据存储 -----
# Room
android_room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "android_room" }
android_room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "android_room" }

# Room-APT
android_room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "android_room" }

# Room-Test
android_room-test = { group = "androidx.room", name = "room-testing", version.ref = "android_room" }


# 编组
[bundles]
# ----- Android：核心 -----
android_core = ["android_appcompat", "android_material", "android_constraintLayout"]
android_coreWithKT = ["android_appcompat", "android_material", "android_constraintLayout", "android_KTX_core", "android_KTX_coroutine", "android_KTX_lifecycleRuntime", "android_KTX_lifecycleViewModel"]


# ----- Android：图像处理 -----
android_coil = ["android_coil-core", "android_coil-gif"]


# Gradle插件
[plugins]
# ----- Kotlin -----
kotlin_core = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_core" }
kotlin_serial = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_core" }
kotlin_ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin_gradle_ksp" }


# ----- Android -----
android_application = { id = "com.android.application", version.ref = "android_agp" }
android_library = { id = "com.android.library", version.ref = "android_agp" }
android_kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_core" }
