# 版本号
[versions]
# ----- Java -----
java_all = "1.0.0"
java_common_base = "1.0.0"
java_io_base = "1.0.0"
java_storage_file = "1.0.0"
java_text_base = "1.0.0"
java_text_gson = "1.0.0"
java_math_base = "1.0.0"
java_security_digest = "1.0.0"

# ----- Android -----


# 组件
[libraries]
# ----- Java -----
java_all = { group = "net.bi4vmr.tool.java", name = "all", version.ref = "java_all" }
java_common_base = { group = "net.bi4vmr.tool.java", name = "common-base", version.ref = "java_common_base" }
java_io_base = { group = "net.bi4vmr.tool.java", name = "io-base", version.ref = "java_io_base" }
java_storage_file = { group = "net.bi4vmr.tool.java", name = "storage-file", version.ref = "java_storage_file" }
java_text_base = { group = "net.bi4vmr.tool.java", name = "text-base", version.ref = "java_text_base" }
java_text_gson = { group = "net.bi4vmr.tool.java", name = "text-gson", version.ref = "java_text_gson" }
java_math_base = { group = "net.bi4vmr.tool.java", name = "math-base", version.ref = "java_math_base" }
java_security_digest = { group = "net.bi4vmr.tool.java", name = "security-digest", version.ref = "java_security_digest" }

# ----- Android -----
